# Makefile for uClibc NPTL
#
# Copyright (C) 2005 Steven J. Hill <sjhill@uclibc.org>
# Portions Copyright (C) 2006 CodeSourcery
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

ASFLAGS-pthread_spin_lock.S = -DNOT_IN_libc -DIS_IN_libpthread
ASFLAGS-pthread_spin_trylock.S = -DNOT_IN_libc -DIS_IN_libpthread

libc_arch_a_CSRC = libc-tls.c
