# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC-y := brk.c syscall.c prctl.c __syscall_error.c

SSRC-y := __longjmp.S bsd-_setjmp.S bsd-setjmp.S clone.S setjmp.S

ifneq ($(UCLIBC_HAS_THREADS_NATIVE),y)
SSRC-y += _vfork.S
endif

# libc-nonshared-y += $(ARCH_OUT)/_syscall.os
